import { Link } from 'react-router-dom';
import { courses as demoCourses, activeProgram } from '../data/demo';
import { useEffect, useState } from 'react';
import { getCourses, createNote } from '../services/contentService';
import { uploadNoteFile } from '../services/storageService';
import { getSession } from '../services/authService';
import { supabaseConfigured } from '../services/supabaseClient';

export default function Courses(){
 const [courses,setCourses]=useState(demoCourses); const [upload,setUpload]=useState(false); const [file,setFile]=useState(null); const [title,setTitle]=useState(''); const [description,setDescription]=useState(''); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
 useEffect(()=>{getCourses(activeProgram).then(setCourses).catch(()=>setCourses(demoCourses));},[]);
 const submit=async e=>{e.preventDefault();setMessage('');if(!file||!title){setMessage('Add a title and choose a file.');return}if(!supabaseConfigured){setMessage('Supabase is not configured yet. Add the Vercel environment variables and run supabase/schema.sql first.');return}setBusy(true);try{const session=await getSession();const path=await uploadNoteFile(file,session?.user?.id);await createNote({title,description,filePath:path,fileType:file.type,userId:session.user.id});setMessage('Note uploaded successfully to your private EngiHub Library.');setFile(null);setTitle('');setDescription('');}catch(err){setMessage(err.message||'Upload failed.')}finally{setBusy(false)}};
 return <div className="container-wide page-pad">
  <div className="course-header"><div><span className="eyebrow">{activeProgram.institution} • {activeProgram.level} • {activeProgram.semester}</span><h1>Your engineering <em>curriculum.</em></h1><p>Courses, summarized notes, visual explainers and practice are organized around your academic context.</p></div><button className="secondary" onClick={()=>setUpload(true)}>＋ Upload notes</button></div>
  <section className="library-hero"><div><span className="eyebrow">ENGINEERING LIBRARY</span><h2>Turn lecture material into a <em>learning experience.</em></h2><p>Upload once. Organize by course and topic. Keep your revision materials in one place.</p><div className="library-points"><span>✓ Private storage</span><span>✓ Course-ready</span><span>✓ Searchable foundation</span></div></div><div className="library-art"><div className="art-grid"/><div className="paper-stack"><span>ENGIHUB</span><b>LECTURE<br/>NOTES</b><small>READ • REVISE • PRACTISE</small></div></div></section>
  <div className="course-grid">{courses.map(c=><Link to={`/topic?course=${encodeURIComponent(c.code)}`} className="big-course" key={c.code}><div className="big-course-image" style={{backgroundImage:`url(${c.image})`}}/><div className="big-course-body"><span>{c.code}</span><h2>{c.name}</h2><p>{c.topics || 0} topics • video • audio • flashcards • practice • PTI questions</p><div className="course-foot"><div className="bar"><i style={{width:(c.progress||0)+'%'}}/></div><b>{c.progress||0}%</b><span>Open course ↗</span></div></div></Link>)}</div>
  <section className="library-strip"><div><span className="eyebrow">CONTENT PIPELINE</span><h2>Your notes are the beginning, not the end.</h2><p>EngiHub is designed to grow from summarized notes into diagrams, flashcards, practice sets, past questions and AI-assisted revision.</p></div><button className="primary" onClick={()=>setUpload(true)}>Add a note →</button></section>
  {upload&&<div className="modal" onMouseDown={()=>!busy&&setUpload(false)}><form className="upload-box" onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><button type="button" className="close" onClick={()=>setUpload(false)}>×</button><span className="eyebrow">MY ENGINEERING LIBRARY</span><h2>Upload a lecture note.</h2><p>PDF, DOCX, PPTX or an image. Files are stored in your private Supabase Storage bucket once the production database is configured.</p><label className="authbox-label">Title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Engineering Mechanics II — Linear Motion"/></label><label className="authbox-label">Description<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Short description of this material" rows="3"/></label><label className="dropzone"><input type="file" accept=".pdf,.ppt,.pptx,.doc,.docx,.png,.jpg,.jpeg" onChange={e=>setFile(e.target.files?.[0]||null)}/><strong>{file?file.name:'Drop your material here'}</strong><small>{file?'Ready to upload':'or tap to browse files'}</small></label>{message&&<div className={message.includes('successfully')?'success':'error'}>{message}</div>}<button className="primary full" disabled={busy}>{busy?'Uploading to Supabase…':'Upload to EngiHub Library →'}</button></form></div>}
 </div>
}
