import { Link } from 'react-router-dom';
export default function Home(){return <div className="home">
 <section className="cinema"><div className="hero-media"/><div className="hero-grid"/><div className="hero-overlay"/><div className="hero-content">
  <div className="eyebrow glow">ENGINEERING EDUCATION, DRAWN TO SCALE.</div>
  <div className="hero-kicker">PTI • FUTURE ENGINEERING LEARNING SYSTEM</div>
  <h1>Learn it.<br/><em>Understand it.</em><br/>Build it.</h1>
  <p>One intelligent engineering environment for clear explanations, video, audio, notes, practice, PTI past questions, AI tutoring and the virtual laboratories of tomorrow.</p>
  <div className="actions"><Link className="primary xl" to="/login">Enter EngiHub <span>↗</span></Link><a className="ghost" href="#ecosystem">Explore the system ↓</a></div>
 </div><div className="hero-specs"><span>01 / LEARN</span><span>02 / PRACTISE</span><span>03 / SIMULATE</span><span>04 / BUILD</span></div><div className="scroll-cue">SCROLL <span>↓</span></div>
 </section>
 <section id="ecosystem" className="statement container-wide"><div><span className="eyebrow">THE PROBLEM</span><h2>Stop switching between five apps just to understand one topic.</h2></div><p>EngiHub brings your lecture notes, easy and engineering explanations, video, audio, flashcards, questions, AI help and school-specific past questions into one focused learning journey.</p></section>
 <section className="experience container-wide"><div className="experience-card big"><span className="eyebrow">01 • UNDERSTAND</span><h2>Simple first.<br/><em>Engineering-deep</em> when you need it.</h2><p>Learn what a concept is, why it exists, how it works, what every variable means and where engineers use it.</p></div><div className="experience-card image-card"><div className="experience-image"/><div><span className="eyebrow">02 • SEE + WATCH</span><h3>Make the invisible visible.</h3><p>Diagrams, realistic imagery, short video explainers and interactive visuals.</p></div></div><div className="experience-card"><span className="eyebrow">03 • PRACTISE</span><h3>Easy → Medium → Hard → PTI.</h3><p>Build confidence before you meet the questions your school actually asks.</p></div><div className="experience-card dark"><span className="eyebrow">04 • ASK AI</span><h3>EngiHub Engine</h3><p>Your course-aware engineering copilot for hints, explanations and mistakes.</p></div></section>
 <section className="lab-banner"><div className="lab-bg"/><div className="lab-content"><span className="eyebrow">ENGINEERING LAB</span><h2>Don't just read about circuits. <em>Build them.</em></h2><p>Virtual practicals will let students connect components, test systems, diagnose faults and experiment safely in a game-like engineering environment.</p><Link className="primary" to="/login">Enter the Lab →</Link></div></section>
 <section className="return-loop container-wide"><span className="eyebrow">THE DAILY LOOP</span><h2>Give students a reason to come back <em>tomorrow.</em></h2><div className="loop-grid">{['Today’s Engineering Mission','Weekly PTI League','Weak-spot recommendation','Daily engineering question','Streak & XP','New practice set'].map((x,i)=><div key={x}><span>0{i+1}</span><b>{x}</b></div>)}</div></section>
 </div>}
