import {useEffect,useState} from 'react';
import {useNavigate,Link} from 'react-router-dom';
import {institutions,departments,levels,courses} from '../data/demo';
import {getSession,login,signup,loginWithGoogle} from '../services/authService';
import {supabaseConfigured} from '../services/supabaseClient';

export default function Login(){
 const nav=useNavigate(); const [mode,setMode]=useState('login'); const [step,setStep]=useState(1);
 const [form,setForm]=useState({name:'',email:'',password:'',institution:institutions[0],department:departments[0],level:levels[0]});
 const [selected,setSelected]=useState(courses.slice(0,3).map(c=>c.code)); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
 const update=(k,v)=>setForm(f=>({...f,[k]:v}));
 useEffect(()=>{ getSession().then(session=>{ if(session?.user){ localStorage.setItem('engihub_user',JSON.stringify({...form,name:session.user.user_metadata?.full_name||session.user.email?.split('@')[0]||'Engineer',email:session.user.email})); nav('/setup',{replace:true}); }}).catch(()=>{}); },[]);
 const saveLocal=(user)=>{localStorage.setItem('engihub_user',JSON.stringify({...form,...user,courses:selected,name:user?.user_metadata?.full_name||form.name||user?.email?.split('@')[0]}));};
 const finish=async()=>{setBusy(true);setError('');try{const data=await signup(form.email,form.password,{full_name:form.name,institution:form.institution,department:form.department,level:form.level}); if(data.session){saveLocal(data.user);nav('/setup')}else{setError('Account created. Check your Gmail inbox and click the Supabase confirmation link before signing in.');setMode('login');setStep(1)}}catch(e){setError(e.message||'Unable to create your account.')}finally{setBusy(false)}};
 const submit=async e=>{e.preventDefault();setError(''); if(mode==='login'){if(!form.email||!form.password){setError('Enter your Gmail and password.');return}setBusy(true);try{const user=await login(form.email,form.password);saveLocal(user);nav('/setup')}catch(e){setError(e.message||'Login failed.')}finally{setBusy(false)}}else if(step<3){if(step===1&&(!form.name||!form.email||form.password.length<6)){setError('Enter your name, Gmail and a password of at least 6 characters.');return}setStep(step+1)}else finish()};
 const google=async()=>{setError('');setBusy(true);try{await loginWithGoogle()}catch(e){setError(e.message||'Google login failed.');setBusy(false)}};
 return <div className="auth-page"><div className="auth-visual"><div className="auth-visual-bg"/><div className="auth-tech">PTI / ENGINEERING / 001</div><div className="auth-copy"><span className="eyebrow">YOUR ENGINEERING WORKSPACE</span><h1>Learn. <em>Practise.</em> Build.</h1><p>Your school, courses, notes, questions and engineering journey in one place.</p></div></div><div className="auth-panel"><Link to="/" className="back">← EngiHub</Link><div className="authbox"><span className="eyebrow">{mode==='login'?'WELCOME BACK':`CREATE WORKSPACE • ${step}/3`}</span><h2>{mode==='login'?'Enter your workspace.':step===1?'Create your account.':step===2?'Tell us where you study.':'Choose what you are learning.'}</h2><p>{mode==='login'?'Sign in securely with Supabase.':step===1?'Create your student account.':step===2?'Choose your school, department and level.':'Accept the recommended curriculum or customize it.'}</p>
 {mode==='login'?<form onSubmit={submit}><button type="button" className="google" disabled={busy||!supabaseConfigured} onClick={google}><span>G</span> Continue with Google</button><div className="or"><i/>or<i/></div><label>Email<input value={form.email} onChange={e=>update('email',e.target.value)} type="email" placeholder="you@gmail.com" autoComplete="email"/></label><label>Password<input value={form.password} onChange={e=>update('password',e.target.value)} type="password" placeholder="••••••••" autoComplete="current-password"/></label>{error&&<div className="error">{error}</div>}<button className="primary full" disabled={busy||!supabaseConfigured}>{busy?'Signing in…':'Sign in →'}</button>{!supabaseConfigured&&<small className="error">Supabase is not configured yet. The app will work after the Vercel environment variables are added.</small>}</form>:<form onSubmit={submit}>{step===1&&<><label>Name<input value={form.name} onChange={e=>update('name',e.target.value)} placeholder="Your name" autoComplete="name"/></label><label>Email<input value={form.email} onChange={e=>update('email',e.target.value)} type="email" placeholder="you@gmail.com" autoComplete="email"/></label><label>Password<input value={form.password} onChange={e=>update('password',e.target.value)} type="password" placeholder="Create a password (6+ characters)" autoComplete="new-password"/></label></>}{step===2&&<div className="select-grid"><label>Institution<select value={form.institution} onChange={e=>update('institution',e.target.value)}>{institutions.map(x=><option key={x}>{x}</option>)}</select></label><label>Department<select value={form.department} onChange={e=>update('department',e.target.value)}>{departments.map(x=><option key={x}>{x}</option>)}</select></label><label>Level<select value={form.level} onChange={e=>update('level',e.target.value)}>{levels.map(x=><option key={x}>{x}</option>)}</select></label></div>}{step===3&&<div className="course-picks">{courses.map(c=><button type="button" className={selected.includes(c.code)?'pick selected':'pick'} key={c.code} onClick={()=>setSelected(s=>s.includes(c.code)?s.filter(x=>x!==c.code):[...s,c.code])}><span>{selected.includes(c.code)?'✓':'+'}</span><div><b>{c.code}</b><strong>{c.name}</strong><small>{c.topics} topics</small></div></button>)}</div>}{error&&<div className="error">{error}</div>}<button className="primary full" disabled={busy||!supabaseConfigured}>{busy?'Creating account…':step===3?'Create my EngiHub account →':'Continue →'}</button></form>}
 <small>{mode==='login'?'New to EngiHub?':'Already have an account?'} <button className="link-button" onClick={()=>{setMode(mode==='login'?'signup':'login');setStep(1);setError('')}}>{mode==='login'?'Create your workspace':'Sign in'}</button></small></div></div></div>
}
